name: app
disk: 4096

type: 'nodejs:14'

web:
    locations:
        '/':
            root: 'public'
            expires: 5m
            allow: true
            scripts: false
            index: ['index.html']
            rules:
                '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
                    expires: 30m

